---
title: "msat.popgen"
author: "Zachary Snider"
date: "2022-10-27"
output: html_document
editor_options: 
  chunk_output_type: console
---

Analysis of Boechera Microsats of SoCal Populations

Loading packages
```{r setup, include=FALSE}
library(ggplot2)
library(ggfortify)
library(tidyverse)
library(polysat)
library(poppr)
library(pegas)
library(adegenet)
library(reshape2)
library(vegan)
library(lattice)
library(RColorBrewer)
library(mmod)
library(ape)
library(magrittr)
library(ggpubr)
library(dartR)
```

```{r}
setwd("~/Desktop/microsats/Rcode")
```

PolySat Analysis
```{r}
msbc <- read.GeneMapper("polysat_msats_californica")
Description(msbc) <- "Boechera californica Microsats collected by ZS"
#Name populations
PopNames(msbc) <- c("SD", "LA", "SJ","SB") 
gpops <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
           2,2,2,2,2,2,2,2,2,
           3,3,3,3,3,3,3,3,3,3,3,1,1)
PopInfo(msbc) <- gpops
PopInfo(msbc)
#Assign ploidy
Ploidies(msbc) <- c(3)
Ploidies(msbc)
#Checking populations
Samples(msbc, populations = "SD")
Samples(msbc, populations = "LA")
Samples(msbc, populations = "SJ")
Samples(msbc, populations = "SB")

#Assigning length of microsats
Usatnts(msbc) <- c(25, 17, 20, 21, 19, 20, 20, 20, 20, 19, 20, 19, 20, 18, 20)
Usatnts(msbc)
```

PCA plots
```{r}
##Genetic distances between individuals
testmatrix <- meandistance.matrix(msbc)
pca1 <- cmdscale(testmatrix)
mycol <- c("#999999","#E69F00","#56B4E9","#009E73")
ggplot(pca1, aes(x=pca1[,1], y=pca1[,2], color= as.character(PopInfo(msbc)))) +
  geom_point(size=2) +
  
  stat_ellipse(geom = "polygon",
               aes(fill = as.character(PopInfo(msbc))), 
               alpha = 0.2) +
  labs(x="Principal Component 1", y="Principal Component 2") +
  labs(title = "PCA with Bruvo Distance using only B. californica") +
  scale_fill_discrete(name ="Regions", labels = c("SD","LA","SJ","SB")) +
  guides(color = "none") + 
  theme_bw(base_size=22)
#Export with 1100 x 700 pixels
#Bruvo distance = takes mutational distance between alleles into account (2004)

testmatrix2 <- meandistance.matrix(msbc, distmetric=Lynch.distance)
pca2 <- cmdscale(testmatrix2)
ggplot(pca2, aes(x=pca2[,1], y=pca2[,2], color= as.character(PopInfo(msbc)))) +
  geom_point(size=2) +
  stat_ellipse(geom = "polygon",
               aes(fill = as.character(PopInfo(msbc))), 
               alpha = 0.2) +
  labs(x="Principal Component 1", y="Principal Component 2") +
  labs(title = "PCA with Lynch Distance using only B. californica") +
  scale_fill_discrete(name ="Regions", labels = c("SD","LA","SJ","SB")) +
  guides(color = "none") +
  theme_bw(base_size=22)
#Export with 1100 x 700 pixels
#Lynch distance = a simple band-sharing measure (1990)
```

Basic Fst calculations
```{r}
genfreqsimple <- simpleFreq(msbc)
genfreqsimple

Fst <- calcPopDiff(genfreqsimple, metric = "Fst")
Fst %>%
  round(digits=5)

#Wright's Gst (1978). States values ranging from 0-0.05 indicate “little” genetic differentiation; 
#0.05-0.15 is “moderate”, 0.15-0.25 is “great”
#microsatellites with high heterozygosity, maximum GST is often 0.1-0.2
Gst <- calcPopDiff(genfreqsimple, metric = "Gst")
Gst %>%
  round(digits=5)

#Rst is a pairwise population genetic distance that is analogous to Fst, 
#but that takes into account differences in the number of repeats between microsatellite alleles (allele size).
Rst <- calcPopDiff(genfreqsimple, metric = "Rst", object = msbc)
Rst %>%
  round(digits=5)
```

Loding in the genclone object
```{r}
cal <- read.genalex("msat_genalex_californica.csv", ploidy=4, geo=FALSE)
cal
```

Using poppr to find stats
```{r}
cal_diversity <- poppr(cal)
cal_diversity
M.tab <- mlg.table(cal)
nLoc(cal) #number of loci
ical <- informloci(cal)
ical #no uninformative loci found
nLoc(ical) #we keep all 15
```

Creating a tree
```{r}
calclust <- find.clusters(cal) #We want the lowest (most negative) BIC
calclust
calreps <- c(25, 17, 20, 21, 19, 20, 20, 20, 20, 19, 20, 19, 20, 18, 20)
calTree <- bruvo.boot(cal,replen = calreps, 
                       cutoff = 50, quiet = T)
#How do groups we found with the clustering algorithm match
#library(RColorBrewer)
cols <- brewer.pal(3, 'Set2')
plot.phylo(calTree, cex = 0.7,
           font = 2, adj = 1,
           tip.color = cols[calclust$grp],
           label.offset = 0.0002)
nodelabels(calTree$node.labels, adj = c(1.3,-0.5),
           frame = 'n',
           cex=0.8, font = 3,
           xpd = T)
axisPhylo(3)
```

Running an amova
```{r}
rho  <- poppr.amova(cal, ~Pop, within = FALSE, cutoff = .1, quiet = TRUE)
rho
```


```{r}
popNames(cal)
strata(cal)
cal2 <- as.genind(cal)
#cal2 <- gl.define.pop(cal,ind.list=c('1.03','2.04'),new='SD', verbose=NULL)
indNames(cal)
popNames(cal)
```


```{r}
cal2 <- read.genalex("msat_genalex_californica2.csv", ploidy=4, geo=FALSE)
popNames(cal2)
strata(cal2)
poppr.amova(cal2, ~Pop, within = FALSE, cutoff = .1, quiet = TRUE)
```

```{r}
p <- c('1','1','1','1','1','1','1','1','1','1',
  '2','2','2','2','2','2','2','2','2','2',
  '3','3','3','3','3','3','3','3','3','3',
  '1','1','1','1','1','1','1','1','1','1',
  '2','2','2','2','2','2','2','2','2','2',
  '1','1','1','1','1')
pop(cal) <- p
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



































