---
title: "Stress.Initial"
author: "Zachary Snider"
date: "2022-10-26"
output: html_document
---

Loading in the required packages
```{r setup, include=FALSE}
library(vegan)
library(FactoMineR)
library(ggplot2)
library(ggfortify)
library(tidyverse)
library(factoextra)
library(gridExtra)
library(car)
library(leaps)
library(picante)
library(hrbrthemes)
library(plotly)
library(tibble)
library(forcats)
library(scales)
library(nlme)
library(lme4)
```

Loading in the data. 
```{r}
setwd("~/Desktop/StressExperiments")
stress <- read.csv("jrpam_all.csv")
recovery <- read.csv("jrpam_5day.csv")
climate <- read.csv("boechera_climate_data.csv")
climate$PopID <- as.factor(climate$PopID)
climate$Individual <- as.factor(climate$Individual)
stress$PopID <- as.factor(stress$PopID)
stress$Individual <- as.factor(stress$Individual)
recovery$PopID <- as.factor(recovery$PopID)
recovery$Individual <- as.factor(recovery$Individual)
colnames(stress) <- c('Individual','PopID','Region','Species',
                      'Heat.Temp','Cotyledon.vs.TL',
                           'rel.ms','Date.Stress','Time.Stress','Fo.prime','No.',
                      'F','Fm.','Temp','YII','Fo','Fm','Fv.Fm')
colnames(recovery) <- c('Individual','PopID','Region','Species','Heat.Temp',
                        'Cotyledon.vs.TL', 'rel.ms','Date.Stress','Time.Stress',
                        'Fo.prime','No.', 'F','Fm.','Temp','YII','Fo','Fm','Fv.Fm')
stress.clim <- left_join(stress, climate, by=c("Individual","Region","PopID","Species"))
colnames(stress.clim) <- c('Individual','PopID','Region','Species','Heat.Temp','Cotyledon.vs.TL','rel.ms','Date.Stress','Time.Stress','Fo.prime','No.','F','Fm.','Temp','YII','Fo','Fm','Fv.Fm','Latitude','Longitude','Elevation','Date.Found','tmean','tmax','tmin','PPT','tdmean','vpdmax','vpdmin','aspect','solclear','soltrans') #Renaming columns for legibility
recovery.clim <- left_join(recovery, climate, by=c("Individual","Region","PopID","Species"))
colnames(recovery.clim) <- c('Individual','PopID','Region','Species','Heat.Temp','Cotyledon.vs.TL','rel.ms','Date.Stress','Time.Stress','Fo.prime','No.','F','Fm.','Temp','YII','Fo','Fm','Fv.Fm','Latitude','Longitude','Elevation','Date.Found','tmean','tmax','tmin','PPT','tdmean','vpdmax','vpdmin','aspect','solclear','soltrans') 
```

Subsetting Data for only CALIFORNICA
```{r}
stress.ca <- stress %>%
  filter(Species == "californica")
recovery.ca <- recovery %>%
  filter(Species == "californica")
stress.clim.ca <- stress.clim %>%
  filter(Species == "californica")
recovery.clim.ca <- recovery.clim %>%
  filter(Species == "californica")
```






















