---
title: "Stress.PhenoScore"
author: "Zachary Snider"
date: "2022-10-26"
output: html_document
---

## R Markdown

Loading in the required packages
```{r setup, include=FALSE}
library(vegan)
library(FactoMineR)
library(ggplot2)
library(ggfortify)
library(tidyverse)
library(factoextra)
library(gridExtra)
library(car)
library(leaps)
library(picante)
library(hrbrthemes)
library(plotly)
library(tibble)
library(forcats)
library(scales)
library(nlme)
library(lme4)
```


Loading in the data. 
```{r}
setwd("~/Desktop/StressExperiments")
### PHENOTYPE DATA ###
pheno <- read.csv("PhenotypeScores.csv")
pheno$Individual <- as.factor(pheno$Individual)
pheno.ca <- pheno %>%
  filter(Species == "californica")
pheno.ca1 <- pivot_longer(pheno.ca, cols = 2:4, names_to = "Time", values_to = "Score")
pheno.ca2 <- aggregate(Score ~ PopID + Time, 
                    data=pheno.ca1, 
                    function(x) { 
                      c(avg=mean(x)) 
                    })
pheno.ca2$PopID <- as.factor(pheno.ca2$PopID)
pheno.ca2$Time <- factor(pheno.ca2$Time, levels=c('Pre.Stress', 'Post.Stress', 'Post.Recovery'))
phenoplot2 <- ggplot(data=pheno.ca2, aes(x=Time, y=PopID,fill=Score)) +
  geom_tile(color="black", lwd=0.08) +
  scale_fill_gradient2(low="#318e1e", mid = "#ffff55", high="#ffffe9", 
                       midpoint = 1.5, na.value = "gray") +
  theme_ipsum() +
  ylab("Subpopulation") +
  xlab("Time") +
  labs(title = "Phenotype Score") +
  scale_x_discrete(labels=c("Pre.Stress" = "Pre Stress", "Post.Stress" = "After Stress",
                            "Post.Recovery" = "After 5 Day Recovery"))
phenoplot2
ggplotly(phenoplot2)
```